### ISSUE TITLE
is 2_Eng.srt always forced?

### ISSUE THREAD

**Issue by goodmoviefan** [ftc2/radarr_import_subs.sh#3]
Hi there, I am needing to implement a similar solution to you (I might even just use your script) and I was wondering how successful you have been in selecting subtitle track 2 as the forced subtitle track? I was thinking I would have to determine this algorithmicly (e.g. checking which subtitle file is the smallest if there are multiple), but you seem to have been satisfied with the assumption that track 2 will usually be the forced track? Thanks.

**Comment by ftc2** [comment]
isn't forced usually track 1? tbh, i so rarely use forced subs, idk. usually i use normal subs anyway (typically track 2)

yes i'm generally satisfied with the assumptions in the script
