### ISSUE TITLE
Is there a way to run this on a Windows radarr installation?

### ISSUE THREAD

**Issue by douglas24** [ftc2/radarr_import_subs.sh#4]
The script ending in .sh gives this error when I try to use it on Windows:
`An error occurred trying to start process 'E:\radarr_import_subs.sh' with working directory 'C:\Windows\system32'. The specified executable is not a valid application for this OS platform.`

**Comment by ftc2** [comment]
maybe possible with wsl2, a vm, docker, cygwin, idk
